[General]
__userfile__=true

[desktopswitch]
alignment=Left

[mount]
alignment=Right

[quicklaunch]
apps\1\desktop=/nix/store/15wdfhhpd0mmapid569iwakrd5gi46l5-system-path/share/applications/qterminal.desktop
apps\size=1

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
